name: Java CI with Gradle

concurrency:
  group: "build-1.21"
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: 21
        distribution: 'zulu'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Remove *-dev.jar
      run: rm ./build/libs/*-dev.jar || true
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: ./build/libs/*.jar
